# Generated by Django 3.1.3 on 2022-04-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0026_auto_20220307_0711'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer_first',
            name='Lab_Lec_Period',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='computer_fourth',
            name='Lab_Lec_Period',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='computer_second',
            name='Lab_Lec_Period',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='computer_third',
            name='Lab_Lec_Period',
            field=models.CharField(blank=True, default=0, max_length=50, null=True),
        ),
    ]
